# Generated by Django 4.0 on 2025-08-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_transacao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
