# Generated by Django 4.0 on 2025-08-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_remove_categoria_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10),
        ),
    ]
