# Generated by Django 5.2.3 on 2025-08-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0010_cartaodecredito_contabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaodecredito',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartaodecredito',
            name='validade',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
