# Generated by Django 4.0 on 2025-08-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0011_cartaodecredito_tipo_cartaodecredito_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.categoria'),
        ),
    ]
