# Generated by Django 5.2.5 on 2025-08-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0012_meta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plano',
            field=models.CharField(default='freemium', max_length=50),
        ),
    ]
