# Generated by Django 5.2.5 on 2025-08-29 01:05

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('financas', 'Profile')
    
    for user in User.objects.all():
        # Verifica se o usuário já tem um perfil
        if not hasattr(user, 'profile'):
            Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0013_profile_plano'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]