# Generated by Django 5.2.5 on 2025-08-29 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0014_auto_20250828_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='nome',
            field=models.CharField(default='Transação Antiga', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
