# Generated by Django 5.2.5 on 2025-08-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0015_transacao_nome_alter_transacao_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('freemium', 'Freemium'), ('pro', 'Pro')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('conteudo_lista', models.TextField(help_text='Lista de itens, separados por ponto e vírgula.')),
            ],
        ),
    ]
