# Generated by Django 5.2.5 on 2025-08-30 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0016_conteudoeducacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaEducacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('freemium', 'Freemium'), ('pro', 'Pro')], default='freemium', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, help_text='Ex: 3 aulas básicas • Aprenda no seu ritmo', max_length=255, null=True)),
                ('descricao_curta', models.TextField(help_text='Descrição breve da aula, aparece no card principal.')),
                ('tempo_estimado_minutos', models.IntegerField(default=15)),
                ('icone', models.CharField(blank=True, help_text="Nome do ícone Lucide (ex: 'book-open')", max_length=50, null=True)),
                ('link_pdf', models.URLField(blank=True, help_text='URL para o PDF da aula', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Aula de Educação',
                'verbose_name_plural': 'Aulas de Educação',
            },
        ),
        migrations.CreateModel(
            name='ParteAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_parte', models.CharField(max_length=200)),
                ('descricao_parte', models.TextField()),
                ('ordem', models.IntegerField(default=0, help_text='Ordem em que a parte aparece na aula')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='financas.aulaeducacao')),
            ],
            options={
                'verbose_name': 'Parte da Aula',
                'verbose_name_plural': 'Partes das Aulas',
                'ordering': ['ordem'],
            },
        ),
        migrations.DeleteModel(
            name='ConteudoEducacao',
        ),
    ]
