# Generated by Django 5.2.5 on 2025-08-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0017_aulaeducacao_parteaula_delete_conteudoeducacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEducacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_curta', models.TextField(help_text='Descrição que aparece no card da página inicial.')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('conteudo_completo', models.TextField(help_text='Conteúdo completo da aula, em HTML ou Markdown.')),
            ],
        ),
        migrations.RemoveField(
            model_name='parteaula',
            name='aula',
        ),
        migrations.DeleteModel(
            name='AulaEducacao',
        ),
        migrations.DeleteModel(
            name='ParteAula',
        ),
    ]
