# Generated by Django 5.2.5 on 2025-08-31 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0018_moduloeducacaofinanceira_remove_parteaula_aula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaEducacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('freemium', 'Freemium'), ('pro', 'Pro')], default='freemium', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_curta', models.TextField(help_text='Descrição breve da aula.')),
                ('tempo_estimado_minutos', models.IntegerField(default=15)),
                ('icone', models.CharField(blank=True, help_text="Nome do ícone Lucide (ex: 'book-open')", max_length=50, null=True)),
                ('link_pdf', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParteAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_parte', models.CharField(max_length=200)),
                ('descricao_parte', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='financas.aulaeducacao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.DeleteModel(
            name='ModuloEducacaoFinanceira',
        ),
    ]
