# Generated by Django 5.2.5 on 2025-08-31 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0019_aulaeducacao_parteaula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('duracao_minutos', models.IntegerField(default=0)),
                ('pdf_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='parteaula',
            options={},
        ),
        migrations.RenameField(
            model_name='parteaula',
            old_name='descricao_parte',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='parteaula',
            old_name='titulo_parte',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='parteaula',
            name='ordem',
        ),
        migrations.AlterField(
            model_name='parteaula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='financas.aula'),
        ),
        migrations.DeleteModel(
            name='AulaEducacao',
        ),
    ]
