# Generated by Django 5.2.5 on 2025-08-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0020_aula_alter_parteaula_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteaula',
            name='subtitulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
