# Generated by Django 5.2.5 on 2025-08-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0021_parteaula_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parteaula',
            name='subtitulo',
        ),
    ]
